export const translations = {
  en: {
    // Header & Nav
    appName: "iFoundAnApple",
    home: "Home",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    register: "Register",
    reportFoundDevice: "Report a Found Device",
    addLostDevice: "Add a Lost Device",
    adminDashboard: "Admin Panel",
    notifications: {
      title: "Notifications",
      markAllAsRead: "Mark all as read",
      noNotifications: "No new notifications.",
      matchFoundOwner: "Match found for your {model}! Action required.",
      matchFoundFinder: "Match found for the {model} you reported. Waiting for owner's payment.",
      paymentReceivedFinder: "Payment received for {model}! Please proceed with the exchange.",
      exchangeConfirmationNeeded: "The other party confirmed the exchange for {model}. Please confirm to complete.",
      transactionCompletedOwner: "Success! The exchange for your {model} is complete.",
      transactionCompletedFinder: "Success! The reward for {model} is on its way.",
    },
    // Home Page
    heroTitle: "Lost your Apple device? Find it securely.",
    heroSubtitle: "We connect you anonymously with the person who found your device. A safe exchange, a fair reward.",
    getStarted: "Get Started",
    howItWorks: "How It Works",
    step1Title: "Owner Reports Lost Device",
    step1Desc: "If you've lost your iPhone, iPad, or Mac, register it on our platform with its serial number.",
    step2Title: "Finder Reports Found Device",
    step2Desc: "Anyone who finds a device can report it anonymously using its serial number.",
    step3Title: "Secure Match & Escrow",
    step3Desc: "Our system automatically matches devices. The owner pays a reward into our secure escrow system.",
    step4Title: "Safe Exchange & Payout",
    step4Desc: "Follow our guidelines for a safe exchange. Once confirmed, the finder receives the reward.",
    // Auth Pages
    loginTitle: "Login to your Account",
    registerTitle: "Create an Account",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    iAmA: "I am a...",
    deviceOwner: "Device Owner",
    deviceFinder: "Device Finder",
    bankInfo: "Bank Account Information (for reward payout)",
    agreeToTerms: "I agree to the {terms} and {privacy}.",
    termsLink: "Terms of Service",
    privacyLink: "Privacy Policy",
    consentRequired: "You must agree to the terms and privacy policy to continue.",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    // Dashboard
    myDevices: "My Devices",
    status: "Status",
    model: "Model",
    serialNumber: "Serial Number",
    noDevicesReported: "You have not reported any devices yet.",
    // Device Forms
    deviceModel: "Device Model (e.g., iPhone 15 Pro)",
    deviceSerialNumber: "Serial Number",
    deviceColor: "Color",
    deviceDescription: "Additional details (optional)",
    deviceInvoice: "Proof of Purchase (Invoice)",
    deviceInvoiceHelper: "Optional. Helps verify ownership.",
    submit: "Submit",
    suggestDescription: "Suggest Description with AI",
    suggestRewardDescription: "Suggest Reward & Description with AI",
    gettingSuggestions: "Getting suggestions...",
    aiSuggestion: "AI Suggestion",
    suggestedReward: "Suggested Reward",
    basedOnValue: "Based on an estimated value of {value}",
    aiError: "Could not get AI suggestions. Please fill in the details manually.",
    // Statuses
    Lost: "Lost",
    Reported: "Reported",
    Matched: "Matched! Awaiting owner payment.",
    PaymentPending: "Matched! Please proceed to payment.",
    PaymentComplete: "Payment Complete! Proceed with exchange.",
    ExchangePending: "Exchange Pending",
    Completed: "Completed",
    // Device Detail Page
    deviceDetails: "Device Details",
    matchFound: "A match was found for your device!",
    reward: "Reward",
    makePaymentSecurely: "Make Payment Securely",
    waitingForOwnerPayment: "Waiting for the owner to make the payment.",
    matchFoundTitle: "Match Found!",
    paymentReceived: "Payment Received!",
    paymentSecureExchange: "Your payment is held securely. Please follow the instructions to complete the exchange and confirm.",
    finderPaymentSecureExchange: "The payment is held securely. Please follow the instructions to complete the exchange and confirm.",
    confirmExchange: "I Confirm the Exchange",
    waitingForOtherParty: "Waiting for the other party to confirm...",
    secureExchangeGuidelines: "Secure Exchange Guidelines",
    guideline1: "Arrange to meet in a safe, public place like a police station or a well-lit cafe.",
    guideline2: "Alternatively, use a tracked and insured shipping service to exchange the device.",
    guideline3: "Do not share personal contact information. Communicate only through our platform if necessary.",
    guideline4: "Once you have successfully exchanged the device, press the confirmation button below.",
    transactionCompleted: "Transaction Completed!",
    transactionCompletedDesc: "The reward has been transferred to the finder. Thank you for using iFoundAnApple.",
    serviceFeeNotice: "A 5% service fee has been deducted from the reward to cover operational costs.",
    backToDashboard: "Back to Dashboard",
    goBack: "Go Back",
    loading: "Loading...",
    viewInvoice: "View Invoice",
    // Admin Panel
    totalUsers: "Total Users",
    totalDevices: "Total Devices",
    allUsers: "All Users",
    allDevices: "All Devices",
    user: "User",
    role: "Role",
    owner: "Owner",
    finder: "Finder",
    admin: "Admin",
    // Footer and Static Pages
    faq: "FAQ",
    terms: "Terms",
    privacy: "Privacy",
    contact: "Contact",
    downloadOnAppStore: "Download on the App Store",
    faqTitle: "Frequently Asked Questions",
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    contactTitle: "Contact Us",
    contactIntro: "If you have any questions or need support, please reach out to us. We're here to help!",
    contactEmail: "support@ifoundanapple.app",
    faqContent: {
      q1: "How does the matching process work?",
      a1: "Our system automatically and anonymously matches a lost device report from an owner with a found device report from a finder based on the device model and serial number. Both parties are notified instantly when a match is found.",
      q2: "Is my personal information safe?",
      a2: "Absolutely. Your privacy is our top priority. We never share your personal information (name, email, etc.) with the other party. All communication and transactions are handled securely through the platform.",
      q3: "How is the reward amount determined?",
      a3: "When reporting a lost device, the owner sets a reward amount. We also offer an AI-powered suggestion feature that recommends a fair reward based on the device's model and estimated second-hand market value.",
      q4: "What is the secure escrow system?",
      a4: "When a match is found, the owner pays the reward amount into our secure escrow system. We hold the payment safely until both parties confirm that the device has been successfully exchanged. This protects both the owner and the finder.",
      q5: "How does the physical exchange happen?",
      a5: "We provide secure exchange guidelines. We strongly recommend meeting in a safe public place (like a police station) or using a tracked, insured shipping service. The platform is designed to facilitate the return without you needing to share personal contact details.",
      q6: "What are the fees?",
      a6: "We deduct a small 5% service fee from the reward amount paid to the finder. This helps us cover operational costs, maintain the platform, and ensure a secure environment for everyone."
    },
    termsContent: `
      <h3 class="text-xl font-semibold mb-2">1. Introduction</h3>
      <p class="mb-4">Welcome to iFoundAnApple. These Terms of Service ("Terms") govern your use of our website and services. By registering an account or using our platform, you agree to be bound by these Terms.</p>
      <h3 class="text-xl font-semibold mb-2">2. The Service</h3>
      <p class="mb-4">iFoundAnApple provides a platform to connect owners of lost Apple devices with individuals who find them ("Finders"). We facilitate this connection through an anonymous matching system and manage a reward payment through a secure escrow process. We are not a party to the physical exchange of any device.</p>
      <h3 class="text-xl font-semibold mb-2">3. User Obligations</h3>
      <p class="mb-4">You agree to provide accurate and truthful information when registering a device. You must be the legal owner of any device you report as lost. You must have lawfully found any device you report as found. You agree not to use the service for any illegal or unauthorized purpose.</p>
      <h3 class="text-xl font-semibold mb-2">4. Payments and Fees</h3>
      <p class="mb-4">Device Owners agree to pay the stated reward amount into our escrow system upon a successful match. This payment is non-refundable once the exchange is completed. We charge a 5% service fee, which is deducted from the reward paid to the Finder. </p>
      <h3 class="text-xl font-semibold mb-2">5. Limitation of Liability</h3>
      <p class="mb-4">iFoundAnApple is a platform provider. We are not responsible for the condition of any returned device, nor are we liable for any issues arising from the physical exchange between users. We provide guidelines for a safe exchange, but the responsibility lies with the users.</p>
    `,
    privacyContent: `
      <h3 class="text-xl font-semibold mb-2">1. Information We Collect</h3>
      <p class="mb-4">We collect information you provide directly to us, such as your name, email address, and device details (model, serial number). For Finders, we also collect bank information solely for the purpose of transferring the reward.</p>
      <h3 class="text-xl font-semibold mb-2">2. How We Use Your Information</h3>
      <p class="mb-4">Your information is used to operate, maintain, and provide the features of our service. Specifically, we use device information for matching and your contact information for sending service-related notifications. We will never share your personal contact or identity information with other users.</p>
      <h3 class="text-xl font-semibold mb-2">3. Data Security</h3>
      <p class="mb-4">We use commercially reasonable physical, administrative, and technological safeguards to preserve the integrity and security of all information collected. However, no security system is impenetrable, and we cannot guarantee the security of our systems 100%.</p>
      <h3 class="text-xl font-semibold mb-2">4. Data Retention</h3>
      <p class="mb-4">We retain your data for as long as your account is active or as needed to provide you services. We may retain some information for compliance with legal obligations, to resolve disputes, and to enforce our agreements.</p>
      <h3 class="text-xl font-semibold mb-2">5. Your Rights (GDPR)</h3>
      <p class="mb-4">You have the right to access, rectify, or erase your personal data. You also have the right to restrict or object to certain processing. To exercise these rights, please contact us at <a href="mailto:privacy@ifoundanapple.app" class="text-brand-blue underline">privacy@ifoundanapple.app</a>.</p>
    `,
  },
  tr: {
    // Header & Nav
    appName: "iFoundAnApple",
    home: "Anasayfa",
    dashboard: "Panel",
    login: "Giriş Yap",
    logout: "Çıkış Yap",
    register: "Kayıt Ol",
    reportFoundDevice: "Bulunan Cihazı Bildir",
    addLostDevice: "Kayıp Cihaz Ekle",
    adminDashboard: "Yönetici Paneli",
    notifications: {
      title: "Bildirimler",
      markAllAsRead: "Tümünü okundu olarak işaretle",
      noNotifications: "Yeni bildirim yok.",
      matchFoundOwner: "{model} cihazınız için eşleşme bulundu! İşlem gerekiyor.",
      matchFoundFinder: "Bildirdiğiniz {model} için eşleşme bulundu. Cihaz sahibinin ödemesi bekleniyor.",
      paymentReceivedFinder: "{model} için ödeme alındı! Lütfen takas işlemine devam edin.",
      exchangeConfirmationNeeded: "Karşı taraf {model} için takası onayladı. Lütfen tamamlamak için siz de onaylayın.",
      transactionCompletedOwner: "Başarılı! {model} cihazınız için takas tamamlandı.",
      transactionCompletedFinder: "Başarılı! {model} için ödülünüz yola çıktı.",
    },
    // Home Page
    heroTitle: "Apple cihazınızı mı kaybettiniz? Güvenle bulun.",
    heroSubtitle: "Sizi, cihazınızı bulan kişiyle anonim olarak bir araya getiriyoruz. Güvenli takas, adil bir ödül.",
    getStarted: "Başla",
    howItWorks: "Nasıl Çalışır?",
    step1Title: "Sahibi Kayıp Cihazı Bildirir",
    step1Desc: "iPhone, iPad veya Mac'inizi kaybettiyseniz, seri numarasıyla platformumuza kaydedin.",
    step2Title: "Bulan Kişi Cihazı Bildirir",
    step2Desc: "Bir cihaz bulan herkes, seri numarasını kullanarak anonim olarak bildirimde bulunabilir.",
    step3Title: "Güvenli Eşleşme ve Ödeme",
    step3Desc: "Sistemimiz cihazları otomatik olarak eşleştirir. Cihaz sahibi, güvenli ödeme sistemimize bir ödül yatırır.",
    step4Title: "Güvenli Takas ve Ödül",
    step4Desc: "Güvenli bir takas için yönergelerimizi izleyin. Takas onaylandığında, bulan kişi ödülü alır.",
    // Auth Pages
    loginTitle: "Hesabınıza Giriş Yapın",
    registerTitle: "Hesap Oluşturun",
    email: "E-posta",
    password: "Şifre",
    fullName: "Ad Soyad",
    iAmA: "Ben bir...",
    deviceOwner: "Cihaz Sahibiyim",
    deviceFinder: "Cihaz Bulanım",
    bankInfo: "Banka Hesap Bilgileri (ödül ödemesi için)",
    agreeToTerms: "{terms} ve {privacy} kabul ediyorum.",
    termsLink: "Hizmet Şartları'nı",
    privacyLink: "Gizlilik Politikası'nı",
    consentRequired: "Devam etmek için hizmet şartlarını ve gizlilik politikasını kabul etmelisiniz.",
    alreadyHaveAccount: "Zaten bir hesabınız var mı?",
    dontHaveAccount: "Hesabınız yok mu?",
    // Dashboard
    myDevices: "Cihazlarım",
    status: "Durum",
    model: "Model",
    serialNumber: "Seri Numarası",
    noDevicesReported: "Henüz herhangi bir cihaz bildiriminde bulunmadınız.",
    // Device Forms
    deviceModel: "Cihaz Modeli (örn. iPhone 15 Pro)",
    deviceSerialNumber: "Seri Numarası",
    deviceColor: "Renk",
    deviceDescription: "Ek detaylar (isteğe bağlı)",
    deviceInvoice: "Satın Alma Kanıtı (Fatura)",
    deviceInvoiceHelper: "İsteğe bağlı. Sahipliği doğrulamaya yardımcı olur.",
    submit: "Gönder",
    suggestDescription: "Yapay Zeka ile Açıklama Öner",
    suggestRewardDescription: "Yapay Zeka ile Ödül ve Açıklama Öner",
    gettingSuggestions: "Öneriler alınıyor...",
    aiSuggestion: "Yapay Zeka Önerisi",
    suggestedReward: "Önerilen Ödül",
    basedOnValue: "{value} tahmini değere göre",
    aiError: "Yapay zeka önerileri alınamadı. Lütfen detayları manuel olarak doldurun.",
    // Statuses
    Lost: "Kayıp",
    Reported: "Bildirildi",
    Matched: "Eşleşti! Cihaz sahibi ödemesi bekleniyor.",
    PaymentPending: "Eşleşti! Lütfen ödemeye devam edin.",
    PaymentComplete: "Ödeme Tamamlandı! Takasa devam edin.",
    ExchangePending: "Takas Bekleniyor",
    Completed: "Tamamlandı",
     // Device Detail Page
    deviceDetails: "Cihaz Detayları",
    matchFound: "Cihazınızla bir eşleşme bulundu!",
    reward: "Ödül",
    makePaymentSecurely: "Ödemeyi Güvenle Yap",
    waitingForOwnerPayment: "Kayıp sahibinin ödeme yapması bekleniyor.",
    matchFoundTitle: "Eşleşme Bulundu!",
    paymentReceived: "Ödeme Alındı!",
    paymentSecureExchange: "Ödemeniz güvende tutuluyor. Lütfen takası tamamlamak ve onaylamak için talimatları izleyin.",
    finderPaymentSecureExchange: "Ödeme güvende tutuluyor. Lütfen takası tamamlamak ve onaylamak için talimatları izleyin.",
    confirmExchange: "Takası Onaylıyorum",
    waitingForOtherParty: "Diğer tarafın onayı bekleniyor...",
    secureExchangeGuidelines: "Güvenli Takas Yönergeleri",
    guideline1: "Karakol veya iyi aydınlatılmış bir kafe gibi güvenli, halka açık bir yerde buluşmayı ayarlayın.",
    guideline2: "Alternatif olarak, cihazı takas etmek için takip edilebilir ve sigortalı bir kargo hizmeti kullanın.",
    guideline3: "Kişisel iletişim bilgilerinizi paylaşmayın. Gerekirse yalnızca platformumuz üzerinden iletişim kurun.",
    guideline4: "Cihazı başarıyla takas ettikten sonra aşağıdaki onay düğmesine basın.",
    transactionCompleted: "İşlem Başarıyla Tamamlandı!",
    transactionCompletedDesc: "Ödül, bulan kişinin hesabına aktarılmıştır. iFoundAnApple'ı kullandığınız için teşekkür ederiz.",
    serviceFeeNotice: "İşletme maliyetlerini karşılamak için ödülden %5'lik bir hizmet bedeli kesilmiştir.",
    backToDashboard: "Panele Geri Dön",
    goBack: "Geri Dön",
    loading: "Yükleniyor...",
    viewInvoice: "Faturayı Görüntüle",
    // Admin Panel
    totalUsers: "Toplam Kullanıcı",
    totalDevices: "Toplam Cihaz",
    allUsers: "Tüm Kullanıcılar",
    allDevices: "Tüm Cihazlar",
    user: "Kullanıcı",
    role: "Rol",
    owner: "Sahip",
    finder: "Bulan",
    admin: "Yönetici",
    // Footer and Static Pages
    faq: "SSS",
    terms: "Şartlar",
    privacy: "Gizlilik",
    contact: "İletişim",
    downloadOnAppStore: "App Store'dan İndir",
    faqTitle: "Sıkça Sorulan Sorular",
    termsTitle: "Hizmet Şartları",
    privacyTitle: "Gizlilik Politikası",
    contactTitle: "Bize Ulaşın",
    contactIntro: "Herhangi bir sorunuz veya desteğe ihtiyacınız olursa, lütfen bize ulaşın. Yardım etmek için buradayız!",
    contactEmail: "destek@ifoundanapple.app",
     faqContent: {
      q1: "Eşleştirme süreci nasıl işliyor?",
      a1: "Sistemimiz, bir cihaz sahibinin kayıp cihaz raporu ile bir bulan kişinin bulduğu cihaz raporunu, cihaz modeli ve seri numarasına göre otomatik ve anonim olarak eşleştirir. Bir eşleşme bulunduğunda her iki taraf da anında bilgilendirilir.",
      q2: "Kişisel bilgilerim güvende mi?",
      a2: "Kesinlikle. Gizliliğiniz bizim önceliğimizdir. Kişisel bilgilerinizi (isim, e-posta vb.) asla diğer tarafla paylaşmayız. Tüm iletişim ve işlemler platform üzerinden güvenli bir şekilde yürütülür.",
      q3: "Ödül miktarı nasıl belirleniyor?",
      a3: "Kayıp bir cihazı bildirirken, sahibi bir ödül miktarı belirler. Ayrıca, cihazın modeline ve tahmini ikinci el piyasa değerine göre adil bir ödül öneren yapay zeka destekli bir öneri özelliği de sunuyoruz.",
      q4: "Güvenli emanet (escrow) sistemi nedir?",
      a4: "Bir eşleşme bulunduğunda, cihaz sahibi ödül miktarını güvenli emanet sistemimize öder. Cihazın başarıyla takas edildiği her iki tarafça onaylanana kadar ödemeyi güvenli bir şekilde tutarız. Bu, hem sahibini hem de bulanı korur.",
      q5: "Fiziksel takas nasıl gerçekleşiyor?",
      a5: "Güvenli takas yönergeleri sunuyoruz. Güvenli bir kamuya açık yerde (karakol gibi) buluşmanızı veya takip edilebilir, sigortalı bir kargo hizmeti kullanmanızı şiddetle tavsiye ederiz. Platform, kişisel iletişim bilgilerinizi paylaşmanıza gerek kalmadan iadeyi kolaylaştırmak için tasarlanmıştır.",
      q6: "Ücretler nelerdir?",
      a6: "Bulana ödenen ödül miktarından küçük bir %5 hizmet bedeli kesiyoruz. Bu, operasyonel maliyetleri karşılamamıza, platformu sürdürmemize ve herkes için güvenli bir ortam sağlamamıza yardımcı olur."
    },
    termsContent: `
      <h3 class="text-xl font-semibold mb-2">1. Giriş</h3>
      <p class="mb-4">iFoundAnApple'a hoş geldiniz. Bu Hizmet Şartları ("Şartlar"), web sitemizi ve hizmetlerimizi kullanımınızı yönetir. Bir hesap oluşturarak veya platformumuzu kullanarak, bu Şartlara bağlı kalmayı kabul etmiş olursunuz.</p>
      <h3 class="text-xl font-semibold mb-2">2. Hizmet</h3>
      <p class="mb-4">iFoundAnApple, kayıp Apple cihazlarının sahiplerini, onları bulan kişilerle ("Bulanlar") bir araya getiren bir platform sağlar. Bu bağlantıyı anonim bir eşleştirme sistemi aracılığıyla kolaylaştırır ve güvenli bir emanet süreciyle ödül ödemesini yönetiriz. Herhangi bir cihazın fiziksel değişiminde taraf değiliz.</p>
      <h3 class="text-xl font-semibold mb-2">3. Kullanıcı Yükümlülükleri</h3>
      <p class="mb-4">Bir cihazı kaydederken doğru ve gerçeğe uygun bilgiler vermeyi kabul edersiniz. Kayıp olarak bildirdiğiniz herhangi bir cihazın yasal sahibi olmalısınız. Bulundu olarak bildirdiğiniz herhangi bir cihazı yasal olarak bulmuş olmalısınız. Hizmeti yasa dışı veya yetkisiz herhangi bir amaç için kullanmamayı kabul edersiniz.</p>
      <h3 class="text-xl font-semibold mb-2">4. Ödemeler ve Ücretler</h3>
      <p class="mb-4">Cihaz Sahipleri, başarılı bir eşleşme üzerine belirtilen ödül tutarını emanet sistemimize ödemeyi kabul eder. Bu ödeme, takas tamamlandıktan sonra iade edilmez. Bulana ödenen ödülden düşülen %5'lik bir hizmet bedeli alıyoruz.</p>
      <h3 class="text-xl font-semibold mb-2">5. Sorumluluğun Sınırlandırılması</h3>
      <p class="mb-4">iFoundAnApple bir platform sağlayıcısıdır. İade edilen herhangi bir cihazın durumundan sorumlu değiliz ve kullanıcılar arasındaki fiziksel takastan kaynaklanan herhangi bir sorundan sorumlu tutulamayız. Güvenli bir takas için yönergeler sunuyoruz, ancak sorumluluk kullanıcılara aittir.</p>
    `,
    privacyContent: `
      <h3 class="text-xl font-semibold mb-2">1. Topladığımız Bilgiler</h3>
      <p class="mb-4">Adınız, e-posta adresiniz ve cihaz detaylarınız (model, seri numarası) gibi doğrudan bize sağladığınız bilgileri toplarız. Bulanlar için, ödülün transferi amacıyla banka bilgilerini de toplarız.</p>
      <h3 class="text-xl font-semibold mb-2">2. Bilgilerinizi Nasıl Kullanırız?</h3>
      <p class="mb-4">Bilgileriniz, hizmetimizin özelliklerini işletmek, sürdürmek ve sağlamak için kullanılır. Özellikle, cihaz bilgilerini eşleştirme için ve iletişim bilgilerinizi hizmetle ilgili bildirimler göndermek için kullanırız. Kişisel iletişim veya kimlik bilgilerinizi asla diğer kullanıcılarla paylaşmayacağız.</p>
      <h3 class="text-xl font-semibold mb-2">3. Veri Güvenliği</h3>
      <p class="mb-4">Toplanan tüm bilgilerin bütünlüğünü ve güvenliğini korumak için ticari olarak makul fiziksel, idari ve teknolojik önlemler kullanıyoruz. Ancak, hiçbir güvenlik sistemi aşılamaz ve sistemlerimizin güvenliğini %100 garanti edemeyiz.</p>
      <h3 class="text-xl font-semibold mb-2">4. Veri Saklama</h3>
      <p class="mb-4">Verilerinizi, hesabınız aktif olduğu sürece veya size hizmet sunmak için gerektiği sürece saklarız. Yasal yükümlülüklere uymak, anlaşmazlıkları çözmek ve anlaşmalarımızı uygulamak için bazı bilgileri saklayabiliriz.</p>
      <h3 class="text-xl font-semibold mb-2">5. Haklarınız (GDPR)</h3>
      <p class="mb-4">Kişisel verilerinize erişme, bunları düzeltme veya silme hakkına sahipsiniz. Ayrıca belirli işlemelere kısıtlama veya itiraz etme hakkınız da vardır. Bu hakları kullanmak için lütfen <a href="mailto:privacy@ifoundanapple.app" class="text-brand-blue underline">privacy@ifoundanapple.app</a> adresinden bizimle iletişime geçin.</p>
    `,
  },
  fr: {
    // Header & Nav
    appName: "iFoundAnApple",
    home: "Accueil",
    dashboard: "Tableau de bord",
    login: "Connexion",
    logout: "Déconnexion",
    register: "S'inscrire",
    reportFoundDevice: "Signaler un appareil trouvé",
    addLostDevice: "Ajouter un appareil perdu",
    adminDashboard: "Panneau d'administration",
    notifications: {
      title: "Notifications",
      markAllAsRead: "Tout marquer comme lu",
      noNotifications: "Aucune nouvelle notification.",
      matchFoundOwner: "Correspondance trouvée pour votre {model} ! Action requise.",
      matchFoundFinder: "Correspondance trouvée pour le {model} que vous avez signalé. En attente du paiement du propriétaire.",
      paymentReceivedFinder: "Paiement reçu pour {model} ! Veuillez procéder à l'échange.",
      exchangeConfirmationNeeded: "L'autre partie a confirmé l'échange pour {model}. Veuillez confirmer pour finaliser.",
      transactionCompletedOwner: "Succès ! L'échange de votre {model} est terminé.",
      transactionCompletedFinder: "Succès ! La récompense pour {model} est en route.",
    },
    // Home Page
    heroTitle: "Vous avez perdu votre appareil Apple ? Retrouvez-le en toute sécurité.",
    heroSubtitle: "Nous vous mettons en contact de manière anonyme avec la personne qui a trouvé votre appareil. Un échange sûr, une récompense juste.",
    getStarted: "Commencer",
    howItWorks: "Comment ça marche ?",
    step1Title: "Le propriétaire signale l'appareil perdu",
    step1Desc: "Si vous avez perdu votre iPhone, iPad ou Mac, enregistrez-le sur notre plateforme avec son numéro de série.",
    step2Title: "Le trouveur signale l'appareil trouvé",
    step2Desc: "Toute personne qui trouve un appareil peut le signaler anonymement en utilisant son numéro de série.",
    step3Title: "Correspondance sécurisée et séquestre",
    step3Desc: "Notre système fait correspondre automatiquement les appareils. Le propriétaire paie une récompense dans notre système de séquestre sécurisé.",
    step4Title: "Échange sûr et paiement",
    step4Desc: "Suivez nos directives pour un échange en toute sécurité. Une fois confirmé, le trouveur reçoit la récompense.",
    // Auth Pages
    loginTitle: "Connectez-vous à votre compte",
    registerTitle: "Créer un compte",
    email: "E-mail",
    password: "Mot de passe",
    fullName: "Nom complet",
    iAmA: "Je suis un(e)...",
    deviceOwner: "Propriétaire d'appareil",
    deviceFinder: "Trouveur d'appareil",
    bankInfo: "Informations de compte bancaire (pour le paiement de la récompense)",
    agreeToTerms: "J'accepte les {terms} et la {privacy}.",
    termsLink: "Conditions d'utilisation",
    privacyLink: "Politique de confidentialité",
    consentRequired: "Vous devez accepter les conditions et la politique de confidentialité pour continuer.",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    // Dashboard
    myDevices: "Mes appareils",
    status: "Statut",
    model: "Modèle",
    serialNumber: "Numéro de série",
    noDevicesReported: "Vous n'avez encore signalé aucun appareil.",
    // Device Forms
    deviceModel: "Modèle de l'appareil (ex: iPhone 15 Pro)",
    deviceSerialNumber: "Numéro de série",
    deviceColor: "Couleur",
    deviceDescription: "Détails supplémentaires (facultatif)",
    deviceInvoice: "Preuve d'achat (Facture)",
    deviceInvoiceHelper: "Facultatif. Aide à vérifier la propriété.",
    submit: "Soumettre",
    suggestDescription: "Suggérer une description avec l'IA",
    suggestRewardDescription: "Suggérer une récompense et une description avec l'IA",
    gettingSuggestions: "Obtention de suggestions...",
    aiSuggestion: "Suggestion de l'IA",
    suggestedReward: "Récompense suggérée",
    basedOnValue: "Basé sur une valeur estimée de {value}",
    aiError: "Impossible d'obtenir les suggestions de l'IA. Veuillez remplir les détails manuellement.",
    // Statuses
    Lost: "Perdu",
    Reported: "Signalé",
    Matched: "Correspondance ! En attente du paiement du propriétaire.",
    PaymentPending: "Correspondance ! Veuillez procéder au paiement.",
    PaymentComplete: "Paiement effectué ! Procédez à l'échange.",
    ExchangePending: "Échange en attente",
    Completed: "Terminé",
    // Device Detail Page
    deviceDetails: "Détails de l'appareil",
    matchFound: "Une correspondance a été trouvée pour votre appareil !",
    reward: "Récompense",
    makePaymentSecurely: "Effectuer le paiement en toute sécurité",
    waitingForOwnerPayment: "En attente du paiement du propriétaire.",
    matchFoundTitle: "Correspondance trouvée !",
    paymentReceived: "Paiement reçu !",
    paymentSecureExchange: "Votre paiement est conservé en toute sécurité. Veuillez suivre les instructions pour finaliser l'échange et confirmer.",
    finderPaymentSecureExchange: "Le paiement est conservé en toute sécurité. Veuillez suivre les instructions pour finaliser l'échange et confirmer.",
    confirmExchange: "Je confirme l'échange",
    waitingForOtherParty: "En attente de la confirmation de l'autre partie...",
    secureExchangeGuidelines: "Directives pour un échange sécurisé",
    guideline1: "Organisez une rencontre dans un lieu public sûr comme un poste de police ou un café bien éclairé.",
    guideline2: "Alternativement, utilisez un service d'expédition avec suivi et assurance pour échanger l'appareil.",
    guideline3: "Ne partagez pas d'informations de contact personnelles. Communiquez uniquement via notre plateforme si nécessaire.",
    guideline4: "Une fois que vous avez échangé l'appareil avec succès, appuyez sur le bouton de confirmation ci-dessous.",
    transactionCompleted: "Transaction terminée !",
    transactionCompletedDesc: "La récompense a été transférée au trouveur. Merci d'utiliser iFoundAnApple.",
    serviceFeeNotice: "Des frais de service de 5% ont été déduits de la récompense pour couvrir les frais opérationnels.",
    backToDashboard: "Retour au tableau de bord",
    goBack: "Retour",
    loading: "Chargement...",
    viewInvoice: "Voir la facture",
    // Admin Panel
    totalUsers: "Utilisateurs totaux",
    totalDevices: "Appareils totaux",
    allUsers: "Tous les utilisateurs",
    allDevices: "Tous les appareils",
    user: "Utilisateur",
    role: "Rôle",
    owner: "Propriétaire",
    finder: "Trouveur",
    admin: "Admin",
    // Footer and Static Pages
    faq: "FAQ",
    terms: "Termes",
    privacy: "Confidentialité",
    contact: "Contact",
    downloadOnAppStore: "Télécharger sur l'App Store",
    faqTitle: "Foire Aux Questions",
    termsTitle: "Conditions d'utilisation",
    privacyTitle: "Politique de confidentialité",
    contactTitle: "Nous contacter",
    contactIntro: "Si vous avez des questions ou avez besoin d'aide, n'hésitez pas à nous contacter. Nous sommes là pour vous aider !",
    contactEmail: "support@ifoundanapple.app",
    faqContent: {
      q1: "Comment fonctionne le processus de correspondance ?",
      a1: "Notre système associe automatiquement et anonymement un rapport d'appareil perdu d'un propriétaire à un rapport d'appareil trouvé d'un trouveur en fonction du modèle et du numéro de série de l'appareil. Les deux parties sont informées instantanément lorsqu'une correspondance est trouvée.",
      q2: "Mes informations personnelles sont-elles en sécurité ?",
      a2: "Absolument. Votre vie privée est notre priorité absolue. Nous ne partageons jamais vos informations personnelles (nom, e-mail, etc.) avec l'autre partie. Toutes les communications et transactions sont gérées en toute sécurité via la plateforme.",
      q3: "Comment le montant de la récompense est-il déterminé ?",
      a3: "Lorsqu'il signale un appareil perdu, le propriétaire fixe le montant de la récompense. Nous proposons également une fonction de suggestion alimentée par l'IA qui recommande une récompense équitable en fonction du modèle de l'appareil et de sa valeur marchande d'occasion estimée.",
      q4: "Qu'est-ce que le système de séquestre sécurisé ?",
      a4: "Lorsqu'une correspondance est trouvée, le propriétaire verse le montant de la récompense dans notre système de séquestre sécurisé. Nous conservons le paiement en toute sécurité jusqu'à ce que les deux parties confirment que l'appareil a été échangé avec succès. Cela protège à la fois le propriétaire et le trouveur.",
      q5: "Comment se déroule l'échange physique ?",
      a5: "Nous fournissons des directives d'échange sécurisées. Nous recommandons vivement de se rencontrer dans un lieu public sûr (comme un poste de police) ou d'utiliser un service d'expédition avec suivi et assurance. La plateforme est conçue pour faciliter la restitution sans que vous ayez besoin de partager vos coordonnées personnelles.",
      q6: "Quels sont les frais ?",
      a6: "Nous déduisons des frais de service modiques de 5 % du montant de la récompense versée au trouveur. Cela nous aide à couvrir les frais de fonctionnement, à maintenir la plateforme et à garantir un environnement sécurisé pour tous."
    },
    termsContent: `...`, // Content should be translated
    privacyContent: `...`, // Content should be translated
  },
  ja: {
    // Header & Nav
    appName: "iFoundAnApple",
    home: "ホーム",
    dashboard: "ダッシュボード",
    login: "ログイン",
    logout: "ログアウト",
    register: "登録",
    reportFoundDevice: "発見したデバイスを報告",
    addLostDevice: "紛失したデバイスを追加",
    adminDashboard: "管理者パネル",
    notifications: {
      title: "通知",
      markAllAsRead: "すべて既読にする",
      noNotifications: "新しい通知はありません。",
      matchFoundOwner: "お使いの{model}に一致するものが見つかりました！対応が必要です。",
      matchFoundFinder: "報告された{model}に一致するものが見つかりました。所有者の支払いを待っています。",
      paymentReceivedFinder: "{model}の支払いを受け取りました！交換手続きに進んでください。",
      exchangeConfirmationNeeded: "相手方が{model}の交換を確認しました。完了するには確認してください。",
      transactionCompletedOwner: "成功！お使いの{model}の交換が完了しました。",
      transactionCompletedFinder: "成功！{model}の報酬が送金中です。",
    },
    // Home Page
    heroTitle: "Appleデバイスを紛失しましたか？安全に見つけましょう。",
    heroSubtitle: "デバイスを見つけた人と匿名で安全に連絡を取ります。安全な交換、公正な報酬。",
    getStarted: "始める",
    howItWorks: "仕組み",
    step1Title: "所有者が紛失デバイスを報告",
    step1Desc: "iPhone、iPad、Macを紛失した場合、シリアル番号をプラットフォームに登録します。",
    step2Title: "発見者が発見デバイスを報告",
    step2Desc: "デバイスを見つけた人は誰でも、シリアル番号を使って匿名で報告できます。",
    step3Title: "安全なマッチングとエスクロー",
    step3Desc: "私たちのシステムは自動的にデバイスを照合します。所有者は安全なエスクローシステムに報酬を支払います。",
    step4Title: "安全な交換と支払い",
    step4Desc: "安全な交換のために私たちのガイドラインに従ってください。確認後、発見者は報酬を受け取ります。",
    // Auth Pages
    loginTitle: "アカウントにログイン",
    registerTitle: "アカウントを作成",
    email: "メールアドレス",
    password: "パスワード",
    fullName: "氏名",
    iAmA: "私は...",
    deviceOwner: "デバイスの所有者",
    deviceFinder: "デバイスの発見者",
    bankInfo: "銀行口座情報（報酬の支払い用）",
    agreeToTerms: "{terms}と{privacy}に同意します。",
    termsLink: "利用規約",
    privacyLink: "プライバシーポリシー",
    consentRequired: "続行するには、利用規約とプライバシーポリシーに同意する必要があります。",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？",
    dontHaveAccount: "アカウントをお持ちではありませんか？",
    // Dashboard
    myDevices: "私のデバイス",
    status: "ステータス",
    model: "モデル",
    serialNumber: "シリアル番号",
    noDevicesReported: "まだデバイスを報告していません。",
    // Device Forms
    deviceModel: "デバイスモデル（例：iPhone 15 Pro）",
    deviceSerialNumber: "シリアル番号",
    deviceColor: "色",
    deviceDescription: "追加情報（任意）",
    deviceInvoice: "購入証明（請求書）",
    deviceInvoiceHelper: "任意。所有権の確認に役立ちます。",
    submit: "送信",
    suggestDescription: "AIで説明を提案",
    suggestRewardDescription: "AIで報酬と説明を提案",
    gettingSuggestions: "提案を取得中...",
    aiSuggestion: "AIの提案",
    suggestedReward: "推奨報酬",
    basedOnValue: "推定価値{value}に基づく",
    aiError: "AIの提案を取得できませんでした。手動で詳細を入力してください。",
    // Statuses
    Lost: "紛失",
    Reported: "報告済み",
    Matched: "一致！所有者の支払いを待っています。",
    PaymentPending: "一致！支払いに進んでください。",
    PaymentComplete: "支払い完了！交換に進んでください。",
    ExchangePending: "交換保留中",
    Completed: "完了",
    // Device Detail Page
    deviceDetails: "デバイス詳細",
    matchFound: "お使いのデバイスに一致するものが見つかりました！",
    reward: "報酬",
    makePaymentSecurely: "安全に支払いを行う",
    waitingForOwnerPayment: "所有者の支払いを待っています。",
    matchFoundTitle: "一致が見つかりました！",
    paymentReceived: "支払いを受け取りました！",
    paymentSecureExchange: "お支払いは安全に保管されています。指示に従って交換を完了し、確認してください。",
    finderPaymentSecureExchange: "支払いは安全に保管されています。指示に従って交換を完了し、確認してください。",
    confirmExchange: "交換を確認します",
    waitingForOtherParty: "相手の確認を待っています...",
    secureExchangeGuidelines: "安全な交換のためのガイドライン",
    guideline1: "警察署や明るいカフェなど、安全な公共の場所で会う約束をしてください。",
    guideline2: "あるいは、追跡・保険付きの配送サービスを利用してデバイスを交換してください。",
    guideline3: "個人の連絡先情報を共有しないでください。必要であれば、私たちのプラットフォームを通じてのみ連絡してください。",
    guideline4: "デバイスの交換が成功したら、下の確認ボタンを押してください。",
    transactionCompleted: "取引完了！",
    transactionCompletedDesc: "報酬は発見者に送金されました。iFoundAnAppleをご利用いただきありがとうございます。",
    serviceFeeNotice: "運営費を賄うため、報酬から5%のサービス手数料が差し引かれました。",
    backToDashboard: "ダッシュボードに戻る",
    goBack: "戻る",
    loading: "読み込み中...",
    viewInvoice: "請求書を見る",
    // Admin Panel
    totalUsers: "総ユーザー数",
    totalDevices: "総デバイス数",
    allUsers: "すべてのユーザー",
    allDevices: "すべてのデバイス",
    user: "ユーザー",
    role: "役割",
    owner: "所有者",
    finder: "発見者",
    admin: "管理者",
    // Footer and Static Pages
    faq: "よくある質問",
    terms: "利用規約",
    privacy: "プライバシー",
    contact: "お問い合わせ",
    downloadOnAppStore: "App Storeでダウンロード",
    faqTitle: "よくあるご質問",
    termsTitle: "利用規約",
    privacyTitle: "プライバシーポリシー",
    contactTitle: "お問い合わせ",
    contactIntro: "ご質問やサポートが必要な場合は、お気軽にお問い合わせください。お手伝いさせていただきます！",
    contactEmail: "support@ifoundanapple.app",
    faqContent: {
        q1: "マッチングプロセスはどのように機能しますか？",
        a1: "当社のシステムは、デバイスのモデルとシリアル番号に基づいて、所有者からの紛失デバイスレポートと発見者からの発見デバイスレポートを自動的かつ匿名で照合します。一致が見つかると、両当事者に即座に通知されます。",
        q2: "個人情報は安全ですか？",
        a2: "もちろんです。お客様のプライバシーは当社の最優先事項です。お客様の個人情報（名前、メールアドレスなど）を相手方と共有することはありません。すべての通信と取引は、プラットフォームを介して安全に処理されます。",
        q3: "報酬額はどのように決定されますか？",
        a3: "紛失したデバイスを報告する際、所有者は報酬額を設定します。また、AIを活用した提案機能も提供しており、デバイスのモデルと推定中古市場価値に基づいて公正な報酬を推奨します。",
        q4: "安全なエスクローシステムとは何ですか？",
        a4: "一致が見つかると、所有者は報酬額を当社の安全なエスクローシステムに支払います。デバイスが正常に交換されたことを両当事者が確認するまで、支払いを安全に保管します。これにより、所有者と発見者の両方が保護されます。",
        q5: "物理的な交換はどのように行われますか？",
        a5: "安全な交換ガイドラインを提供しています。安全な公共の場所（警察署など）で会うか、追跡・保険付きの配送サービスを利用することを強くお勧めします。このプラットフォームは、個人連絡先を共有することなく返却を容易にするように設計されています。",
        q6: "手数料はかかりますか？",
        a6: "発見者に支払われる報酬額から5％の少額のサービス手数料を差し引きます。これは、運営費をカバーし、プラットフォームを維持し、すべての人のための安全な環境を確保するのに役立ちます。"
    },
    termsContent: `...`, // Content should be translated
    privacyContent: `...`, // Content should be translated
  },
  es: {
    // Header & Nav
    appName: "iFoundAnApple",
    home: "Inicio",
    dashboard: "Panel",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    register: "Registrarse",
    reportFoundDevice: "Reportar un Dispositivo Encontrado",
    addLostDevice: "Añadir un Dispositivo Perdido",
    adminDashboard: "Panel de Admin",
    notifications: {
      title: "Notificaciones",
      markAllAsRead: "Marcar todo como leído",
      noNotifications: "No hay notificaciones nuevas.",
      matchFoundOwner: "¡Se encontró una coincidencia para tu {model}! Se requiere acción.",
      matchFoundFinder: "Se encontró una coincidencia para el {model} que reportaste. Esperando el pago del propietario.",
      paymentReceivedFinder: "¡Pago recibido por {model}! Por favor, procede con el intercambio.",
      exchangeConfirmationNeeded: "La otra parte confirmó el intercambio de {model}. Por favor, confirma para completar.",
      transactionCompletedOwner: "¡Éxito! El intercambio de tu {model} se ha completado.",
      transactionCompletedFinder: "¡Éxito! La recompensa por {model} está en camino.",
    },
    // Home Page
    heroTitle: "¿Perdiste tu dispositivo Apple? Encuéntralo de forma segura.",
    heroSubtitle: "Te conectamos anónimamente con la persona que encontró tu dispositivo. Un intercambio seguro, una recompensa justa.",
    getStarted: "Comenzar",
    howItWorks: "¿Cómo funciona?",
    step1Title: "El Propietario Reporta el Dispositivo Perdido",
    step1Desc: "Si has perdido tu iPhone, iPad o Mac, regístralo en nuestra plataforma con su número de serie.",
    step2Title: "El Encontrador Reporta el Dispositivo Encontrado",
    step2Desc: "Cualquier persona que encuentre un dispositivo puede reportarlo anónimamente usando su número de serie.",
    step3Title: "Coincidencia Segura y Depósito",
    step3Desc: "Nuestro sistema empareja automáticamente los dispositivos. El propietario paga una recompensa en nuestro sistema de depósito seguro.",
    step4Title: "Intercambio Seguro y Pago",
    step4Desc: "Sigue nuestras pautas para un intercambio seguro. Una vez confirmado, el encontrador recibe la recompensa.",
    // Auth Pages
    loginTitle: "Inicia sesión en tu cuenta",
    registerTitle: "Crear una cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    fullName: "Nombre completo",
    iAmA: "Soy un...",
    deviceOwner: "Propietario de dispositivo",
    deviceFinder: "Encontrador de dispositivo",
    bankInfo: "Información de la cuenta bancaria (para el pago de la recompensa)",
    agreeToTerms: "Acepto los {terms} y la {privacy}.",
    termsLink: "Términos de Servicio",
    privacyLink: "Política de Privacidad",
    consentRequired: "Debes aceptar los términos y la política de privacidad para continuar.",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    dontHaveAccount: "¿No tienes una cuenta?",
    // Dashboard
    myDevices: "Mis Dispositivos",
    status: "Estado",
    model: "Modelo",
    serialNumber: "Número de serie",
    noDevicesReported: "Aún no has reportado ningún dispositivo.",
    // Device Forms
    deviceModel: "Modelo del dispositivo (ej: iPhone 15 Pro)",
    deviceSerialNumber: "Número de serie",
    deviceColor: "Color",
    deviceDescription: "Detalles adicionales (opcional)",
    deviceInvoice: "Prueba de compra (Factura)",
    deviceInvoiceHelper: "Opcional. Ayuda a verificar la propiedad.",
    submit: "Enviar",
    suggestDescription: "Sugerir descripción con IA",
    suggestRewardDescription: "Sugerir recompensa y descripción con IA",
    gettingSuggestions: "Obteniendo sugerencias...",
    aiSuggestion: "Sugerencia de IA",
    suggestedReward: "Recompensa sugerida",
    basedOnValue: "Basado en un valor estimado de {value}",
    aiError: "No se pudieron obtener las sugerencias de la IA. Por favor, rellena los detalles manualmente.",
    // Statuses
    Lost: "Perdido",
    Reported: "Reportado",
    Matched: "¡Coincidencia! Esperando pago del propietario.",
    PaymentPending: "¡Coincidencia! Por favor, procede al pago.",
    PaymentComplete: "¡Pago completado! Procede con el intercambio.",
    ExchangePending: "Intercambio Pendiente",
    Completed: "Completado",
    // Device Detail Page
    deviceDetails: "Detalles del Dispositivo",
    matchFound: "¡Se encontró una coincidencia para tu dispositivo!",
    reward: "Recompensa",
    makePaymentSecurely: "Realizar Pago de Forma Segura",
    waitingForOwnerPayment: "Esperando a que el propietario realice el pago.",
    matchFoundTitle: "¡Coincidencia Encontrada!",
    paymentReceived: "¡Pago Recibido!",
    paymentSecureExchange: "Tu pago se retiene de forma segura. Por favor, sigue las instrucciones para completar el intercambio y confirmar.",
    finderPaymentSecureExchange: "El pago se retiene de forma segura. Por favor, sigue las instrucciones para completar el intercambio y confirmar.",
    confirmExchange: "Confirmo el Intercambio",
    waitingForOtherParty: "Esperando la confirmación de la otra parte...",
    secureExchangeGuidelines: "Pautas para un Intercambio Seguro",
    guideline1: "Acuerda reunirte en un lugar público y seguro como una comisaría o una cafetería bien iluminada.",
    guideline2: "Alternativamente, utiliza un servicio de envío con seguimiento y seguro para intercambiar el dispositivo.",
    guideline3: "No compartas información de contacto personal. Comunícate solo a través de nuestra plataforma si es necesario.",
    guideline4: "Una vez que hayas intercambiado el dispositivo con éxito, presiona el botón de confirmación a continuación.",
    transactionCompleted: "¡Transacción Completada!",
    transactionCompletedDesc: "La recompensa ha sido transferida al encontrador. Gracias por usar iFoundAnApple.",
    serviceFeeNotice: "Se ha deducido una tarifa de servicio del 5% de la recompensa para cubrir los costos operativos.",
    backToDashboard: "Volver al Panel",
    goBack: "Volver",
    loading: "Cargando...",
    viewInvoice: "Ver Factura",
    // Admin Panel
    totalUsers: "Usuarios Totales",
    totalDevices: "Dispositivos Totales",
    allUsers: "Todos los Usuarios",
    allDevices: "Todos los Dispositivos",
    user: "Usuario",
    role: "Rol",
    owner: "Propietario",
    finder: "Encontrador",
    admin: "Admin",
    // Footer and Static Pages
    faq: "Preguntas Frecuentes",
    terms: "Términos",
    privacy: "Privacidad",
    contact: "Contacto",
    downloadOnAppStore: "Descargar en la App Store",
    faqTitle: "Preguntas Frecuentes",
    termsTitle: "Términos de Servicio",
    privacyTitle: "Política de Privacidad",
    contactTitle: "Contáctanos",
    contactIntro: "Si tienes alguna pregunta o necesitas ayuda, no dudes en contactarnos. ¡Estamos aquí para ayudarte!",
    contactEmail: "soporte@ifoundanapple.app",
    faqContent: {
        q1: "¿Cómo funciona el proceso de emparejamiento?",
        a1: "Nuestro sistema empareja de forma automática y anónima un informe de dispositivo perdido de un propietario con un informe de dispositivo encontrado de un buscador basándose en el modelo y el número de serie del dispositivo. Ambas partes son notificadas al instante cuando se encuentra una coincidencia.",
        q2: "¿Está segura mi información personal?",
        a2: "Absolutamente. Tu privacidad es nuestra máxima prioridad. Nunca compartimos tu información personal (nombre, correo electrónico, etc.) con la otra parte. Todas las comunicaciones y transacciones se manejan de forma segura a través de la plataforma.",
        q3: "¿Cómo se determina el importe de la recompensa?",
        a3: "Al informar de un dispositivo perdido, el propietario establece un importe de recompensa. También ofrecemos una función de sugerencia impulsada por IA que recomienda una recompensa justa basada en el modelo del dispositivo y el valor de mercado de segunda mano estimado.",
        q4: "¿Qué es el sistema de depósito seguro (escrow)?",
        a4: "Cuando se encuentra una coincidencia, el propietario paga el importe de la recompensa en nuestro sistema de depósito seguro. Mantenemos el pago de forma segura hasta que ambas partes confirmen que el dispositivo se ha intercambiado con éxito. Esto protege tanto al propietario como al buscador.",
        q5: "¿Cómo se realiza el intercambio físico?",
        a5: "Proporcionamos pautas de intercambio seguro. Recomendamos encarecidamente reunirse en un lugar público seguro (como una comisaría) o utilizar un servicio de envío con seguimiento y seguro. La plataforma está diseñada para facilitar la devolución sin necesidad de que compartas datos de contacto personales.",
        q6: "¿Cuáles son las tarifas?",
        a6: "Deducimos una pequeña tarifa de servicio del 5% del importe de la recompensa pagada al buscador. Esto nos ayuda a cubrir los costes operativos, mantener la plataforma y garantizar un entorno seguro para todos."
    },
    termsContent: `...`, // Content should be translated
    privacyContent: `...`, // Content should be translated
  },
};